services:
  - type: web
    name: whiteboardpro
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python web_service.py
    envVars:
      - key: PORT
        value: 10000
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_PRICE_ID
        sync: false
      - key: STRIPE_PAYMENT_LINK
        value: https://buy.stripe.com/test_5kQ28rfZdd2RablaVicQU02
        sync: false
    autoDeploy: true
